export enum Status {
  berserk = 'berserk',
  confuse = 'confuse',
  curse = 'curse',
  darkness = 'darkness',
  death = 'death',
  drain = 'drain',
  petrify = 'petrify',
  poison = 'poison',
  silence = 'silence',
  sleep = 'sleep',
  slow = 'slow',
  stop = 'stop',
  zombie = 'zombie',
}

export const ALL_STATUS = [
  Status.berserk,
  Status.confuse,
  Status.curse,
  Status.darkness,
  Status.death,
  Status.drain,
  Status.petrify,
  Status.poison,
  Status.silence,
  Status.sleep,
  Status.slow,
  Status.stop,
  Status.zombie,
];
