export enum Status {
  berserk = 'berserk',
  confuse = 'confuse',
  curse = 'curse',
  darkness = 'darkness',
  death = 'death',
  drain = 'drain',
  petrify = 'petrify',
  poison = 'poison',
  silence = 'silence',
  sleep = 'sleep',
  slow = 'slow',
  stop = 'stop',
  zombie = 'zombie',
}
